### ISSUE TITLE
Localization [Question]

### ISSUE THREAD

**Issue by smaragdus** [azlotnikov/Keep2Me#2]
Hello,

I did a quick test of Keep2Me version 0.9.9.9 but I could not find a way to switch language from Russian to English. I had a look in settings (Настройки) but I could not find settings related to language. I can understand some basic Russian but I am not very comfortable with it. Is English supported? If not- are there plans for localization of the program?

Regards

**Comment by azlotnikov** [comment]
Hi! 
I don't support this app anymore (except rare updates of screenshot hosters), so there are no plans for localization ;(

**Comment by smaragdus** [comment]
@azlotnikov 

Thanks for your quick response. You may close this issue or keep it open in case you change your mind in the future.

Regards
