### ISSUE TITLE
ошибка при загрузки любого скрина 

### ISSUE THREAD

**Issue by victor20010** [azlotnikov/Keep2Me#3]
---------------------------
Keep2Me
---------------------------
Invalid pointer operation.
---------------------------
ОК   
---------------------------

пробывал запускать и от админа и без админа

**Comment by azlotnikov** [comment]
Скорее всего выбран нерабочий загрузчик на определенный хостинг. По идее должна еще работать загрузка на i.zhyk.ru
Попробуйте ее. Остальное могло уже устареть и не работает.

**Comment by victor20010** [comment]
> 
ого быстрый ответ , да вы верно сказали спс) , пользуюсь со времен как сидел на жуке) прога тооооп
